// User Roles
export type UserRole = 'student' | 'lecturer' | 'admin';

// User Base Interface
export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  department: string;
  avatar?: string;
}

// Student Interface
export interface Student extends User {
  role: 'student';
  matricNumber: string;
  level: number;
  enrolledCourses: string[];
  attendanceRate: number;
}

// Lecturer Interface
export interface Lecturer extends User {
  role: 'lecturer';
  staffId: string;
  assignedCourses: string[];
}

// Admin Interface
export interface Admin extends User {
  role: 'admin';
  staffId: string;
  position: string;
}

// Course Interface
export interface Course {
  id: string;
  code: string;
  title: string;
  description: string;
  lecturerId: string;
  lecturerName: string;
  department: string;
  level: number;
  schedule: CourseSchedule;
  totalStudents: number;
  color: string;
}

export interface CourseSchedule {
  day: string;
  startTime: string;
  endTime: string;
  room: string;
}

// Attendance Record Interface
export interface AttendanceRecord {
  id: string;
  courseId: string;
  courseCode: string;
  courseTitle: string;
  studentId: string;
  studentName: string;
  studentMatric: string;
  lecturerId: string;
  date: string;
  time: string;
  status: 'present' | 'absent' | 'late';
  sessionId: string;
  verificationMode?: 'qr' | 'bluetooth-qr';
  bluetoothDeviceName?: string;
  bluetoothDeviceId?: string;
}

export interface BluetoothSessionConfig {
  sessionId?: string;
  requiresBluetooth?: boolean;
  bluetoothDeviceName?: string;
  bluetoothServiceUuid?: string;
  courseTitle?: string;
}

export interface BluetoothVerificationContext {
  bluetoothVerified?: boolean;
  bluetoothDeviceName?: string;
  bluetoothDeviceId?: string;
}

// Active Session Interface (Generated by Lecturer)
export interface ActiveSession {
  id: string;
  courseId: string;
  courseCode: string;
  courseTitle: string;
  lecturerId: string;
  lecturerName: string;
  barcodeData: string;
  createdAt: string;
  expiresAt: string;
  duration: number; // in minutes
  scannedStudents: string[];
  totalStudents: number;
  room: string;
  isActive: boolean;
  requiresBluetooth?: boolean;
  bluetoothDeviceName?: string;
  bluetoothServiceUuid?: string;
}

// Dashboard Stats
export interface StudentStats {
  attendanceRate: number;
  classesToday: number;
  totalScans: number;
  streakDays: number;
}

export interface LecturerStats {
  totalStudents: number;
  todayAttendanceRate: number;
  activeSessions: number;
  totalCourses: number;
}

export interface AdminStats {
  totalUsers: number;
  totalStudents: number;
  totalLecturers: number;
  activeClassesToday: number;
  systemUptime: string;
  alerts: number;
}

// Scan Result
export interface ScanResult {
  success: boolean;
  message: string;
  courseName?: string;
  timestamp?: string;
}

// Navigation Item
export interface NavItem {
  label: string;
  icon: string;
  path: string;
  roles: UserRole[];
}

// Toast Notification
export interface Toast {
  id: string;
  type: 'success' | 'error' | 'warning' | 'info';
  message: string;
  duration?: number;
}
